# see https://juliadocs.github.io/Documenter.jl/dev/man/hosting/#GitHub-Actions
# add this file to the repository once you set up authentication as described in the Documenter manual

name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  Documenter:
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-docdeploy@latest 
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
